# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rate2scale <- function(rate, shape) {
    .Call('_baclava_rate2scale', PACKAGE = 'baclava', rate, shape)
}

update_scales <- function(theta) {
    .Call('_baclava_update_scales', PACKAGE = 'baclava', theta)
}

dloglik_sojourn_P_List <- function(data_objects, age_at_tau_hp_hats, indolents, theta) {
    .Call('_baclava_dloglik_sojourn_P_List', PACKAGE = 'baclava', data_objects, age_at_tau_hp_hats, indolents, theta)
}

dloglik_screens_List <- function(data_objects, age_at_tau_hp_hats, theta) {
    .Call('_baclava_dloglik_screens_List', PACKAGE = 'baclava', data_objects, age_at_tau_hp_hats, theta)
}

compute_prob_tau_obj <- function(data_object, theta, t0) {
    .Call('_baclava_compute_prob_tau_obj', PACKAGE = 'baclava', data_object, theta, t0)
}

compute_prob_tau_List <- function(data_objects, theta, t0) {
    .Call('_baclava_compute_prob_tau_List', PACKAGE = 'baclava', data_objects, theta, t0)
}

rprop_age_at_tau_hp_hat_obj <- function(data_object, prob_tau, theta, t0) {
    .Call('_baclava_rprop_age_at_tau_hp_hat_obj', PACKAGE = 'baclava', data_object, prob_tau, theta, t0)
}

rprop_age_at_tau_hp_hat_List <- function(data_objects, prob_tau, theta, t0) {
    .Call('_baclava_rprop_age_at_tau_hp_hat_List', PACKAGE = 'baclava', data_objects, prob_tau, theta, t0)
}

compute_prob_indolent_obj <- function(data_object, theta, age_at_tau_hp_hat) {
    .Call('_baclava_compute_prob_indolent_obj', PACKAGE = 'baclava', data_object, theta, age_at_tau_hp_hat)
}

compute_prob_indolent_List <- function(data_objects, age_at_tau_hp_hats, theta) {
    .Call('_baclava_compute_prob_indolent_List', PACKAGE = 'baclava', data_objects, age_at_tau_hp_hats, theta)
}

rprop_indolent_obj <- function(data_object, prob_indolent) {
    .Call('_baclava_rprop_indolent_obj', PACKAGE = 'baclava', data_object, prob_indolent)
}

rprop_indolent_List <- function(data_objects, prob_indolents) {
    .Call('_baclava_rprop_indolent_List', PACKAGE = 'baclava', data_objects, prob_indolents)
}

dlog_prop_indolent_obj <- function(data_object, prob_indolent, indolent) {
    .Call('_baclava_dlog_prop_indolent_obj', PACKAGE = 'baclava', data_object, prob_indolent, indolent)
}

dlog_prop_latent_obj <- function(data_object, prob_tau, theta, age_at_tau_hp_hat, prob_indolent, indolent, t0) {
    .Call('_baclava_dlog_prop_latent_obj', PACKAGE = 'baclava', data_object, prob_tau, theta, age_at_tau_hp_hat, prob_indolent, indolent, t0)
}

MCMC_cpp_internal <- function(data_objects, indolents, prior, age_at_tau_hp_hats, theta, epsilon_rate_H, epsilon_rate_P, epsilon_psi, t0, M, thin, M_thin, n_obs, n_screen_positive_total, adaptive, verbose, save_latent) {
    .Call('_baclava_MCMC_cpp_internal', PACKAGE = 'baclava', data_objects, indolents, prior, age_at_tau_hp_hats, theta, epsilon_rate_H, epsilon_rate_P, epsilon_psi, t0, M, thin, M_thin, n_obs, n_screen_positive_total, adaptive, verbose, save_latent)
}

model_comparison <- function(data_object, theta, t0, indolent_phase) {
    .Call('_baclava_model_comparison', PACKAGE = 'baclava', data_object, theta, t0, indolent_phase)
}

